# Generated by Django 5.2.4 on 2025-07-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='rating',
            field=models.FloatField(default=0, help_text='Average rating from 0 to 5'),
        ),
    ]
