# Generated by Django 5.2.4 on 2025-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_turf_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='available_time_slots',
            field=models.CharField(blank=True, help_text="Comma-separated list of available time slots, e.g. '09:00-10:00,10:00-11:00'", max_length=255),
        ),
    ]
