# Generated by Django 5.2.4 on 2025-07-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
